### ISSUE TITLE
Syntax Error when using with python 3.7 on ubuntu

### ISSUE THREAD

**Issue by somas1** [benmezger/pydebug#1]
I get the following error immediately when importing pydebug on an Ubuntu Bionic machine: 
from pydebug import PDBDebugger
print xmlformat(text, encoding)    SyntaxError: invalid syntax

**Comment by benmezger** [comment]
@somas1 this issue is not related to `pydebug` as `pydebug` does not import any `XML` library. Although I see you are using `print` as a statement, this has changed in Python 3.
What you are looking for is:

```python
from pydebug import PDBDebugger

print(xmlformat(text, encoding))
```
